### ISSUE TITLE
Crash when players join server.

### ISSUE THREAD

**Issue by knoxhack** [Stormwind99/FoodFunk#30]
**Describe the bug**
Crash when players join a server even if their player data is wiped.

**Logs**
https://gist.github.com/knoxhack/ef6c4ca8c28ccb367977cb9fc648be48

**Comment by Stormwind99** [comment]
The log says versions were Food Funk 4.0.3 and Wumple Util 2.5.0.

That NPE crash should already be fixed in the latest FoodFunk and WumpleUtil versions.

Please update to the recent releases of Food Funk 4.2.0 and Wumple Util 2.8.32 and try again.  It should not crash, but if it does please re-open issue with a new log and foodfunk.cfg attached.

**Comment by knoxhack** [comment]
Oh yeah, I forgot to report it but I can't update to latest version of FoodFunk because latest cause huge FPS drop down to 1. any idea why?

**Comment by Stormwind99** [comment]
I can't duplicate the drop in FPS - any chance it is a diifferent mod?  You can add and remove just the foodfunk mod to see.

Can you please re-test, and if still an issue, attach latest.log and foodfunk.cfg to this issue?
