### ISSUE TITLE
Crashes with BOP

### ISSUE THREAD

**Issue by Novotisy** [Stormwind99/FoodFunk#41]
**Describe the bug**
Crashes with Biomes O Plenty installed both client and server side

**Logs*
[latest.log](https://github.com/Stormwind99/FoodFunk/files/2365057/latest.log)

**Config files**
Default Config Files

**Comment by Stormwind99** [comment]
I could not duplicate this crash with Biomes O Plenty, Food Funk, and Wumple Util mods loaded.

Along with the crash log, I'd guess this crash is caused by one of the other installed mods misbehaving and doing bad things.  

To find the bad mod, try disabling all mods other than BOP, Food Funk, and Wumple Util, then enable the mods one at a time (well, plus any dependencies for the newly enabled mod) and see which one causes the crash.

This crash should not be possible normally due to the NPE checks:
`Caused by: java.lang.NullPointerException
	at net.minecraft.item.ItemStack.setTagCompound(ItemStack.java:597) ~[aip.class:?]
	at net.minecraft.item.ItemStack.setTagInfo(ItemStack.java:951) ~[aip.class:?]
	at net.minecraft.item.ItemStack.getOrCreateSubCompound(ItemStack.java:571) ~[aip.class:?]
	at com.wumple.foodfunk.capability.rot.Rot.forceUpdate(Rot.java:192) ~[Rot.class:4.6.1]`

**Comment by Stormwind99** [comment]
Food Funk 4.9.6 may have a workaround for this crash - can you try it out?
