### ISSUE TITLE
Crafted food already rotted

### ISSUE THREAD

**Issue by T3chW0lf20** [Stormwind99/FoodFunk#57]
**Describe the bug**
I wanted to make something last a long time, erse jam in my case, but when I craft it, it's automaticaly 96% rotten

**To Reproduce**
1. change craft-able food items "days to rot" to 200
2. craft item in game
3. item is already at 193 days

**Expected behavior**
I expect the item to last 200 days, but now it just lasts 7.

**Logs**
[2019-05-25-6.log.gz](https://github.com/Stormwind99/FoodFunk/files/3219881/2019-05-25-6.log.gz)

**Comment by Codetoil** [comment]
Items that are rotted combine to produce rotted food.
What is likely happening is that the ingredients of erse jam are already rotted, meaning that this is likely intentional.

**Comment by Stormwind99** [comment]
@Codetoil  is correct - to avoid cheating away the rot of food by crafting new items out of rotting food, Food Funk transfers the rot of ingredients to the crafted item.

See the following code from Wumple Util (my library that Food Funk uses):
* [com.wumple.util.capability.eventtimed.IEventTimedThingCap.copyFrom(IEventTimedThingCap<W, T>, World)](https://github.com/Stormwind99/WumpleUtil/blob/3de3cc5a8af1c3353c4037d4093858eb9638d07e/src/main/java/com/wumple/util/capability/eventtimed/IEventTimedThingCap.java#L185)
* [com.wumple.util.capability.eventtimed.IEventTimedThingCap.handleCraftedTimers(World, IInventory, ItemStack)](https://github.com/Stormwind99/WumpleUtil/blob/3de3cc5a8af1c3353c4037d4093858eb9638d07e/src/main/java/com/wumple/util/capability/eventtimed/IEventTimedThingCap.java#L366)
* [com.wumple.util.capability.eventtimed.ThingTimerEventHandler.onCrafted(ItemCraftedEvent)](https://github.com/Stormwind99/WumpleUtil/blob/bbe5fc2368f7580033da8b44219b39fc87046158/src/main/java/com/wumple/util/capability/eventtimed/ThingTimerEventHandler.java#L150)

It has been a while since I wrote it and these code comments might be outdated, but here is some info from ThingTimerEventHandler.onCrafted:

>         // Avoid cheating from crafting or break rotting items
>         
>         // For example: 
>         // Melon 0/14 days -> Slices 0/7 days -> Melon 0/7 days or 7/14 days
>         // Melon 8/14 days -> Slices 6/7 days -> Melon 6/7 days or 13/14 days
>         // Crafting: Ingredients 1/7, 2/7, 3/7 days -> Results 3/7 days
>         // Crafting: Ingredients 1/7, 2/7, 3/7 days -> Results 10/14 days
>         // Crafting: Ingredients 5/14, 6/14 -> Results 0/7 days
>         // Crafting: Ingredients 6/14, 9/14 -> Results 2/7 days

I'll close this issue assuming this (crafting food from rotting food) is the case, but if it isn't feel free to comment and we can re-open the issue.
